{% set version = "4.5.1" %}

package:
  name: podman-py
  version: {{ version }}

source:
  url: https://github.com/containers/podman-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 464631a8005e61a5118c2d408f373a327efb854074b70ef6e24985d90c0b2231

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - pyxdg >=0.26
    - setuptools
    - requests >=2.24
    - tomli >=1.2.3                # [py<311]
    - typing_extensions            # [py<=38]
    - urllib3 >=1.26.5,<2.0.0
  run:
    - python
    - pyxdg >=0.26
    - requests >=2.24
    - tomli >=1.2.3                # [py<311]
    - typing_extensions            # [py<=38]
    - urllib3 >=1.26.5,<2.0.0

test:
  imports:
    - podman

about:
  home: https://github.com/containers/podman-py
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python bindings and code examples for using Varlink access to Podman Service
  dev_url: https://github.com/containers/podman-py

extra:
  recipe-maintainers:
    - alippai
    - h-vetinari
    - '4383'
