{% set version = "1.6.0" %}

package:
  name: podman-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/podman/podman-{{ version }}.tar.gz
  sha256: 5f6493ee9087126f1cd8f5e2bff708cada59f841aef6ea0ee594efbb5b17916c

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: true  # [py<3 or win]

requirements:
  host:
    - pbr
    - pip
    - python >=3
    - setuptools
  run:
    - pbr
    - psutil
    - python >=3
    - python-dateutil
    - setuptools
    - varlink

test:
  imports:
    - podman

about:
  home: https://github.com/containers/python-podman
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Python bindings and code examples for using Varlink access to Podman Service"
  dev_url: https://github.com/containers/python-podman

extra:
  recipe-maintainers:
    - h-vetinari
    - "4383"
